version: '3.1'

services:
    db:
        image: mysql:latest
        environment:
          - MYSQL_ROOT_PASSWORD=123456
          - MYSQL_USER=sentiment
          - MYSQL_PASSWORD=123456
          - MYSQL_DATABASE=sentiment
        restart: always
        healthcheck:
            test: mysqladmin -uroot -p123456 ping
            interval: 2s
            timeout: 5s
            retries: 30
        ports:
          - 13306:3306
        volumes:
          - ./mysql-data:/var/lib/mysql
