FROM python:3

WORKDIR /app 


COPY ./requirements.txt /app/requirements.txt

RUN apt-get update
RUN pip install -r requirements.txt

RUN pip install scikit-learn

COPY ./engine /app
ENTRYPOINT ["python","job_v1.py"]


