version: '3'

services:
  standalone-chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
  redis:
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]



networks:
  elastic:
volumes:
  esdata:
    driver: local