version: '3'

services:
  standalone-chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
  redis:
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]

  #elasticsearch:
   # image: elasticsearch:7.6.2
    #environment:
     # - http.host=0.0.0.0
     # - transport.host=0.0.0.0
     # - bootstrap.memory_lock=true
     # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #ulimits:
    #  memlock:
    #    soft: -1
    #    hard: -1
    #ports:
    #  - "9200:9200"
    #networks:
    #  - elastic
    #volumes:
    #  - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    #  - esdata:/usr/share/elasticsearch/data
  #kibana:
  #  image: kibana:7.6.2
  #  ports:
  #    - 5601:5601
  #  networks:
  #    - elastic
  #  volumes:
  #    - ./kibana.yml:/usr/share/kibana/config/kibana.yml
  #  depends_on:
  #    - elasticsearch
#networks:
#  elastic:
#volumes:
#  esdata:
#    driver: local